name: Scrape Telegram and Update data.json

on:
  schedule:
    # ⚠️ GitHub cron min interval is 5 min by doc. 1-min “hack” using repository_dispatch via self-call, see note below.
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install requests beautifulsoup4 deep-translator
      - run: python scrape_translate.py
      - name: Commit and push data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main --rebase
          git add data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push origin main
