name: Scrape Telegram and Update data.json

on:
  schedule:
    - cron: "*/15 * * * *"  # La fiecare 15 minute
  workflow_dispatch:        # Poți rula manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 deep-translator

      - name: Run Telegram scraper
        run: python scrape_translate.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push
