name: Scrape Telegram and Update data.json

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 deep-translator

      - name: Run scraping script
        run: python scrape_translate.py

      - name: Debug - list files
        run: |
          echo "Listing files:"
          ls -la
          echo "Contents of data.json:"
          cat data.json

      - name: Commit and push data.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update data.json"
            git push origin main
          fi
